In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
df=pd.read_csv('Training_Data.csv')

In [2]:
df.head()


Id   Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
0   1  1303834   23           3         single          rented            no   
1   2  7574516   40          10         single          rented            no   
2   3  3991815   66           4        married          rented            no   
3   4  6256451   41           2         single          rented           yes   
4   5  5768871   47          11         single          rented            no   

            Profession                 CITY           STATE  CURRENT_JOB_YRS  \
0  Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
1   Software_Developer             Parbhani     Maharashtra                9   
2     Technical_writer            Alappuzha          Kerala                4   
3   Software_Developer          Bhubaneswar          Odisha                2   
4        Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   

   CURRENT_HOUSE_YRS  Risk_Flag  
0                 13          0  
1                 13          0  
2                 10          0  
3                 12          1  
4                 14          1

In [3]:
df.shape

(252000, 13)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252000 entries, 0 to 251999
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   Id                 252000 non-null  int64 
 1   Income             252000 non-null  int64 
 2   Age                252000 non-null  int64 
 3   Experience         252000 non-null  int64 
 4   Married/Single     252000 non-null  object
 5   House_Ownership    252000 non-null  object
 6   Car_Ownership      252000 non-null  object
 7   Profession         252000 non-null  object
 8   CITY               252000 non-null  object
 9   STATE              252000 non-null  object
 10  CURRENT_JOB_YRS    252000 non-null  int64 
 11  CURRENT_HOUSE_YRS  252000 non-null  int64 
 12  Risk_Flag          252000 non-null  int64 
dtypes: int64(7), object(6)
memory usage: 25.0+ MB


In [5]:
df.isnull().sum()

Id                   0
Income               0
Age                  0
Experience           0
Married/Single       0
House_Ownership      0
Car_Ownership        0
Profession           0
CITY                 0
STATE                0
CURRENT_JOB_YRS      0
CURRENT_HOUSE_YRS    0
Risk_Flag            0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import category_encoders as ce

# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows  
# how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

In [7]:
label_encoder = LabelEncoder()

for col in ['Married/Single','Car_Ownership']:
    df[col] = label_encoder.fit_transform( df[col] )

In [8]:
pd.get_dummies(df, columns=["House_Ownership"])

Id   Income  Age  Experience  Married/Single  Car_Ownership  \
0            1  1303834   23           3               1              0   
1            2  7574516   40          10               1              0   
2            3  3991815   66           4               0              0   
3            4  6256451   41           2               1              1   
4            5  5768871   47          11               1              0   
...        ...      ...  ...         ...             ...            ...   
251995  251996  8154883   43          13               1              0   
251996  251997  2843572   26          10               1              0   
251997  251998  4522448   46           7               1              0   
251998  251999  6507128   45           0               1              0   
251999  252000  9070230   70          17               1              0   

                 Profession                 CITY           STATE  \
0       Mechanical_engineer                 Rewa  Madhya_Pradesh   
1        Software_Developer             Parbhani     Maharashtra   
2          Technical_writer            Alappuzha          Kerala   
3        Software_Developer          Bhubaneswar          Odisha   
4             Civil_servant  Tiruchirappalli[10]      Tamil_Nadu   
...                     ...                  ...             ...   
251995              Surgeon              Kolkata     West_Bengal   
251996         Army_officer                 Rewa  Madhya_Pradesh   
251997      Design_Engineer      Kalyan-Dombivli     Maharashtra   
251998     Graphic_Designer          Pondicherry      Puducherry   
251999         Statistician                Avadi      Tamil_Nadu   

        CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  Risk_Flag  \
0                     3                 13          0   
1                     9                 13          0   
2                     4                 10          0   
3                     2                 12          1   
4                     3                 14          1   
...                 ...                ...        ...   
251995                6                 11          0   
251996                6                 11          0   
251997                7                 12          0   
251998                0                 10          0   
251999                7                 11          0   

        House_Ownership_norent_noown  House_Ownership_owned  \
0                                  0                      0   
1                                  0                      0   
2                                  0                      0   
3                                  0                      0   
4                                  0                      0   
...                              ...                    ...   
251995                             0                      0   
251996                             0                      0   
251997                             0                      0   
251998                             0                      0   
251999                             0                      0   

        House_Ownership_rented  
0                            1  
1                            1  
2                            1  
3                            1  
4                            1  
...                        ...  
251995                       1  
251996                       1  
251997                       1  
251998                       1  
251999                       1  

[252000 rows x 15 columns]

In [9]:
onehot_encoder = OneHotEncoder(sparse = False)
df['House_Ownership'] = onehot_encoder.fit_transform(df['House_Ownership'].values.reshape(-1, 1) )

In [10]:
high_card_features = ['Profession', 'CITY', 'STATE']

count_encoder = ce.CountEncoder()

# Transform the features, rename the columns with the _count suffix, and join to dataframe
count_encoded = count_encoder.fit_transform( df[high_card_features] )
df = df.join(count_encoded.add_suffix("_count"))

In [11]:
df= df.drop(labels=['Profession', 'CITY', 'STATE'], axis=1)
df.head()

Id   Income  Age  Experience  Married/Single  House_Ownership  \
0   1  1303834   23           3               1              0.0   
1   2  7574516   40          10               1              0.0   
2   3  3991815   66           4               0              0.0   
3   4  6256451   41           2               1              0.0   
4   5  5768871   47          11               1              0.0   

   Car_Ownership  CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  Risk_Flag  \
0              0                3                 13          0   
1              0                9                 13          0   
2              0                4                 10          0   
3              1                2                 12          1   
4              0                3                 14          1   

   Profession_count  CITY_count  STATE_count  
0              5217         798        14122  
1              5053         849        25562  
2              5195         688         5805  
3              5053         607         4658  
4              4413         809        16537

In [12]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, info_gain=None, value=None):
        ''' constructor ''' 
        
        # for decision node
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
        self.info_gain = info_gain
        
        # for leaf node
        self.value = value

In [13]:
class DecisionTreeClassifier():
    def __init__(self, min_samples_split=2, max_depth=2):
        ''' constructor '''
        
        # initialize the root of the tree 
        self.root = None
        
        # stopping conditions
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        
    def build_tree(self, dataset, curr_depth=0):
        ''' recursive function to build the tree ''' 
        
        X, Y = dataset[:,:-1], dataset[:,-1]
        num_samples, num_features = np.shape(X)
        
        # split until stopping conditions are met
        if num_samples>=self.min_samples_split and curr_depth<=self.max_depth:
            # find the best split
            best_split = self.get_best_split(dataset, num_samples, num_features)
            # check if information gain is positive
            if best_split["info_gain"]>0:
                # recur left
                left_subtree = self.build_tree(best_split["dataset_left"], curr_depth+1)
                # recur right
                right_subtree = self.build_tree(best_split["dataset_right"], curr_depth+1)
                # return decision node
                return Node(best_split["feature_index"], best_split["threshold"], 
                            left_subtree, right_subtree, best_split["info_gain"])
        
        # compute leaf node
        leaf_value = self.calculate_leaf_value(Y)
        # return leaf node
        return Node(value=leaf_value)
    
    def get_best_split(self, dataset, num_samples, num_features):
        ''' function to find the best split '''
        
        # dictionary to store the best split
        best_split = {}
        max_info_gain = -float("inf")
        
        # loop over all the features
        for feature_index in range(num_features):
            feature_values = dataset[:, feature_index]
            possible_thresholds = np.unique(feature_values)
            # loop over all the feature values present in the data
            for threshold in possible_thresholds:
                # get current split
                dataset_left, dataset_right = self.split(dataset, feature_index, threshold)
                # check if childs are not null
                if len(dataset_left)>0 and len(dataset_right)>0:
                    y, left_y, right_y = dataset[:, -1], dataset_left[:, -1], dataset_right[:, -1]
                    # compute information gain
                    curr_info_gain = self.information_gain(y, left_y, right_y, "gini")
                    # update the best split if needed
                    if curr_info_gain>max_info_gain:
                        best_split["feature_index"] = feature_index
                        best_split["threshold"] = threshold
                        best_split["dataset_left"] = dataset_left
                        best_split["dataset_right"] = dataset_right
                        best_split["info_gain"] = curr_info_gain
                        max_info_gain = curr_info_gain
                        
        # return best split
        return best_split
    
    def split(self, dataset, feature_index, threshold):
        ''' function to split the data '''
        
        dataset_left = np.array([row for row in dataset if row[feature_index]<=threshold])
        dataset_right = np.array([row for row in dataset if row[feature_index]>threshold])
        return dataset_left, dataset_right
    
    def information_gain(self, parent, l_child, r_child, mode="entropy"):
        ''' function to compute information gain '''
        
        weight_l = len(l_child) / len(parent)
        weight_r = len(r_child) / len(parent)
        if mode=="gini":
            gain = self.gini_index(parent) - (weight_l*self.gini_index(l_child) + weight_r*self.gini_index(r_child))
        else:
            gain = self.entropy(parent) - (weight_l*self.entropy(l_child) + weight_r*self.entropy(r_child))
        return gain
    
    def entropy(self, y):
        ''' function to compute entropy '''
        
        class_labels = np.unique(y)
        entropy = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            entropy += -p_cls * np.log2(p_cls)
        return entropy
    
    def gini_index(self, y):
        ''' function to compute gini index '''
        
        class_labels = np.unique(y)
        gini = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            gini += p_cls**2
        return 1 - gini
        
    def calculate_leaf_value(self, Y):
        ''' function to compute leaf node '''
        
        Y = list(Y)
        return max(Y, key=Y.count)
    
    def print_tree(self, tree=None, indent=" "):
        ''' function to print the tree '''
        
        if not tree:
            tree = self.root

        if tree.value is not None:
            print(tree.value)

        else:
            print("X_"+str(tree.feature_index), "<=", tree.threshold, "?", tree.info_gain)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)
    
    def fit(self, X, Y):
        ''' function to train the tree '''
        
        dataset = np.concatenate((X, Y), axis=1)
        self.root = self.build_tree(dataset)
    
    def predict(self, X):
        ''' function to predict new dataset '''
        
        preditions = [self.make_prediction(x, self.root) for x in X]
        return preditions
    
    def make_prediction(self, x, tree):
        ''' function to predict a single data point '''
        
        if tree.value!=None: return tree.value
        feature_val = x[tree.feature_index]
        if feature_val<=tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)

In [14]:
Y = df["Risk_Flag"].values.reshape(-1,1)
print (Y)
Y.shape

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


(252000, 1)

In [15]:
X = df.drop("Risk_Flag", axis=1).values
print (X)
X.shape

[[1.000000e+00 1.303834e+06 2.300000e+01 ... 5.217000e+03 7.980000e+02
  1.412200e+04]
 [2.000000e+00 7.574516e+06 4.000000e+01 ... 5.053000e+03 8.490000e+02
  2.556200e+04]
 [3.000000e+00 3.991815e+06 6.600000e+01 ... 5.195000e+03 6.880000e+02
  5.805000e+03]
 ...
 [2.519980e+05 4.522448e+06 4.600000e+01 ... 4.729000e+03 7.410000e+02
  2.556200e+04]
 [2.519990e+05 6.507128e+06 4.500000e+01 ... 5.166000e+03 8.970000e+02
  1.433000e+03]
 [2.520000e+05 9.070230e+06 7.000000e+01 ... 5.806000e+03 6.670000e+02
  1.653700e+04]]


(252000, 12)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.2, random_state=41)

In [25]:
X_train_subset, y_train_subset = X_train[:10000], Y_train[:10000]
X_test_subset, y_test_subset = X_test[:10000], Y_test[:10000]

In [26]:
print (Y_test)

[[0]
 [0]
 [1]
 ...
 [0]
 [0]
 [0]]


In [34]:
classifier = DecisionTreeClassifier(min_samples_split=3, max_depth=8)
classifier.fit(X_train_subset,y_train_subset)

In [35]:
Y_pred = classifier.predict(X_test_subset) 
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score, roc_auc_score

print (recall_score(y_test_subset, Y_pred))
print (precision_score(y_test_subset, Y_pred))
print (f1_score(y_test_subset, Y_pred))
print (accuracy_score(y_test_subset, Y_pred))

0.053125
0.288135593220339
0.08970976253298153
0.862


In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_subset, Y_pred)
print(cm)

[[8552  168]
 [1212   68]]


In [30]:
classifier = DecisionTreeClassifier(min_samples_split=3, max_depth=5)
classifier.fit(X_train_subset,y_train_subset)

In [33]:
Y_pred = classifier.predict(X_test_subset) 
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score, roc_auc_score

print (recall_score(y_test_subset, Y_pred))
print (precision_score(y_test_subset, Y_pred))
print (f1_score(y_test_subset, Y_pred))
print (accuracy_score(y_test_subset, Y_pred))

0.0078125
0.2857142857142857
0.015209125475285171
0.8705


In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_subset, Y_pred)
print(cm)

[[8695   25]
 [1270   10]]
